import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {

  return (
    <div className="text-3xl font-bold ">
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="container">
        <ConnectButton />

        <h1 className="">
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-3xl font-bold underline">
          Get started by editing{' '}
          <code className="">pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
